import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from config import Settings
from email_template import build_ticket_content
from schemas import DefectDojoFinding, EmailPayload, ProjectEmailMappingConfig, TicketAction
from sla import policy_for_severity
from smtp_client import SmtpClient


def resolve_first_recipient(settings: Settings) -> tuple[str, str]:
    if not settings.project_email_mapping_json:
        raise ValueError("PROJECT_EMAIL_MAPPING_JSON is required")

    mapping = ProjectEmailMappingConfig.model_validate(
        json.loads(settings.project_email_mapping_json)
    )
    for project in mapping.projects:
        if project.email_destinations:
            return project.product_name, str(project.email_destinations[0])
    raise ValueError("No recipient found in PROJECT_EMAIL_MAPPING_JSON")


def main() -> int:
    settings = Settings()
    product_name, recipient = resolve_first_recipient(settings)
    finding = DefectDojoFinding(
        finding_id=900001,
        title="Synthetic SMTP/ManageEngine Incoming Mail Test",
        severity="Low",
        product=product_name,
        endpoint="synthetic.example.test/login",
        date="2026-06-12",
        description=(
            "This is a synthetic test email generated by the DevSecOps Auto "
            "Ticket lab. It does not contain a real security finding."
        ),
        mitigation="Confirm that ManageEngine Incoming Mail creates a request.",
        scanner_type="Synthetic Test",
        rule_id="SYNTHETIC-GMAIL-INCOMING-TEST",
    )
    dedupe_key = "dd:synthetic-gmail-incoming-test"
    sla_policy = policy_for_severity(finding.severity)
    content = build_ticket_content(
        finding,
        settings.defectdojo_base_url,
        dedupe_key=dedupe_key,
        sla_policy=sla_policy,
        ticket_action=TicketAction.CREATE,
        group=settings.manageengine_default_group,
        category=settings.manageengine_default_category,
        subcategory=settings.manageengine_default_subcategory,
    )
    payload = EmailPayload(
        finding_id=content.finding_id,
        recipient_email=recipient,
        subject=content.subject,
        body=content.body,
        html_body=content.html_body,
        dedupe_key=content.dedupe_key,
        priority=content.priority,
        sla_target=content.sla_target,
        ticket_action=content.ticket_action,
    )

    SmtpClient(settings).send(payload)

    print("SENT_SYNTHETIC_EMAIL")
    print(f"finding_id={finding.finding_id}")
    print(f"product={product_name}")
    print(f"recipient={recipient}")
    print(f"subject={content.subject}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
